name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Docker Compose
        run: |
          pip install docker-compose

      - name: Build and Run Tests
        run: |
          docker-compose build
          docker-compose run app sh -c "python manage.py test && flake8"
